---
# https://docs.microsoft.com/de-de/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-3.1

- git:
    repo: https://github.com/JournalMd/JournalMdServer.git
    dest: "{{journalmd_server_dir}}"


# BUG? Sometimes 3.x is missing?!
- name: Install dotnet core (again?)
  apt:
    name: "{{ dotnet_package }}"
    state: present
    update_cache: yes


- name: Create appsettings config file
  template:
    src: templates/appsettings.Production.json.j2
    dest: "{{journalmd_server_dir}}/out/appsettings.Production.json"
    owner: root
    group: root
    mode: 0644


- name: dotnet restore
  command: dotnet restore JournalMd.sln
  args:
    chdir: "{{journalmd_server_dir}}"
  environment:
    ASPNETCORE_ENVIRONMENT=Production

- name: dotnet publish
  command: dotnet publish JournalMd.sln --configuration Release -o out
  args:
    chdir: "{{journalmd_server_dir}}"
  environment:
    ASPNETCORE_ENVIRONMENT=Production


- name: dotnet ef database update
  command: dotnet ef database update
  args:
    chdir: "{{journalmd_server_dir}}"
  environment:
    ASPNETCORE_ENVIRONMENT=Production


- name: Make sure service is stopped
  systemd:
    state: stopped
    name: "{{ journalmd_name }}"
  ignore_errors: yes

- name: "service killall"
  shell: killall {{ journalmd_name }}
  ignore_errors: yes

- name: Create service file
  template:
    src: templates/journalmd.service.j2
    dest: /etc/systemd/system/{{ journalmd_name }}.service
    owner: root
    group: root
    mode: 0644

- name: Make sure service is started
  systemd:
    state: started
    enabled: yes
    name: "{{ journalmd_name }}"
  ignore_errors: yes
