---
# https://cli.vuejs.org/guide/deployment.html

- name: Create directory
  file:
    path: "{{journalmd_clientweb_dir}}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0775

- git:
    repo: https://github.com/JournalMd/JournalMdClientWeb.git
    dest: "{{journalmd_clientweb_dir}}"
    force: yes


- name: Create env config file
  template:
    src: templates/env.j2
    dest: "{{journalmd_clientweb_dir}}/.env"
    owner: root
    group: root
    mode: 0644

- name: yarn install
  command: /usr/bin/yarn install
  args:
    chdir: "{{journalmd_clientweb_dir}}"

- name: yarn build
  command: /usr/bin/yarn build
  args:
    chdir: "{{journalmd_clientweb_dir}}"
