---
- include: mysql_create.yml
  when: journalmd_server_install|bool

- include: journalmdserver_install.yml
  when: journalmd_server_install|bool

- include: journalmdclientweb_install.yml
  when: journalmd_clientweb_install|bool
